# Includes
### 1. Sorting dataframes
### 2. Merging dataframes

In [2]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('bigmart_data.csv')
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [8]:
#find the count of null values in each column
data.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [9]:
# dropping the null values
data = data.dropna(how='any')
data.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [10]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088

#  1. Sorting Dataframes

### <ol>1. sort_values(): to sort pandas dataframe by one or more columns
###  <ol>2. sort_index(): to sort pandas dataframe by row index

In [11]:
# sorting by Item_Weight

sorted_data = data.sort_values(by='Item_Weight')
sorted_data.head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
3489,FDP40,4.555,Regular,0.034351,Frozen Foods,112.7544,OUT035,2004,Small,Tier 2,Supermarket Type1,1789.6704
7808,FDP40,4.555,Regular,0.034329,Frozen Foods,110.1544,OUT013,1987,High,Tier 3,Supermarket Type1,1230.3984
4400,FDP40,4.555,Regular,0.034411,Frozen Foods,111.3544,OUT049,1999,Medium,Tier 1,Supermarket Type1,1342.2528
4430,FDP40,4.555,Regular,0.034357,Frozen Foods,112.6544,OUT046,1997,Small,Tier 1,Supermarket Type1,2684.5056
6432,DRE12,4.590,Low Fat,0.070722,Soft Drinks,113.2860,OUT013,1987,High,Tier 3,Supermarket Type1,1471.4180
1082,DRE12,4.590,Low Fat,0.070891,Soft Drinks,111.6860,OUT049,1999,Medium,Tier 1,Supermarket Type1,1584.6040
1515,DRE12,4.590,Low Fat,0.070781,Soft Drinks,114.5860,OUT046,1997,Small,Tier 1,Supermarket Type1,1245.0460
3077,DRE12,4.590,Low Fat,0.070767,Soft Drinks,111.9860,OUT035,2004,Small,Tier 2,Supermarket Type1,792.3020
6335,DRF23,4.610,Low Fat,0.122629,Hard Drinks,175.4396,OUT035,2004,Small,Tier 2,Supermarket Type1,2616.5940
7559,DRF23,4.610,Low Fat,0.123152,Hard Drinks,175.2396,OUT018,2009,Medium,Tier 3,Supermarket Type2,2093.2752

In [14]:
''' sort_value() has multiple parameters like:
        1. ascending: takes boolean value, True for ascending order, False for descending order
        2. inplace: whether to do inplace sorting or not. Reflets the changes in the original dataframe
'''
data.sort_values(by='Item_Weight', ascending=False, inplace=True)
data.head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
4468,FDC02,21.35,Low Fat,0.068822,Canned,258.3278,OUT046,1997,Small,Tier 1,Supermarket Type1,7028.8506
2368,FDC02,21.35,Low Fat,0.068809,Canned,258.5278,OUT035,2004,Small,Tier 2,Supermarket Type1,5206.5560
2802,FDC02,21.35,Low Fat,0.068765,Canned,260.4278,OUT013,1987,High,Tier 3,Supermarket Type1,3644.5892
43,FDC02,21.35,Low Fat,0.069103,Canned,259.9278,OUT018,2009,Medium,Tier 3,Supermarket Type2,6768.5228
6389,FDR07,21.35,Low Fat,0.078061,Fruits and Vegetables,96.0094,OUT018,2009,Medium,Tier 3,Supermarket Type2,380.8376
8221,NCO42,21.25,Low Fat,0.024756,Household,146.7102,OUT018,2009,Medium,Tier 3,Supermarket Type2,1603.9122
6705,FDA45,21.25,Low Fat,0.156013,Snack Foods,177.3370,OUT018,2009,Medium,Tier 3,Supermarket Type2,2822.9920
3632,FDT03,21.25,Low Fat,0.010039,Meat,181.7608,OUT018,2009,Medium,Tier 3,Supermarket Type2,1102.5648
5959,FDQ21,21.25,low fat,0.019407,Snack Foods,119.3756,OUT013,1987,High,Tier 3,Supermarket Type1,3271.7412
5111,NCO42,21.25,LF,0.024651,Household,146.0102,OUT035,2004,Small,Tier 2,Supermarket Type1,2916.2040

In [15]:
data = pd.read_csv('bigmart_data.csv')
data = data.dropna(how='any')

In [17]:
#Sorting data based on multiple columns
#Sorts the data by firsdt sorting the first column name passed and then sorting the second column
data.sort_values(by=['Item_Weight', 'Item_MRP'], ascending=False).head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
2802,FDC02,21.35,Low Fat,0.068765,Canned,260.4278,OUT013,1987,High,Tier 3,Supermarket Type1,3644.5892
43,FDC02,21.35,Low Fat,0.069103,Canned,259.9278,OUT018,2009,Medium,Tier 3,Supermarket Type2,6768.5228
2368,FDC02,21.35,Low Fat,0.068809,Canned,258.5278,OUT035,2004,Small,Tier 2,Supermarket Type1,5206.5560
4468,FDC02,21.35,Low Fat,0.068822,Canned,258.3278,OUT046,1997,Small,Tier 1,Supermarket Type1,7028.8506
6389,FDR07,21.35,Low Fat,0.078061,Fruits and Vegetables,96.0094,OUT018,2009,Medium,Tier 3,Supermarket Type2,380.8376
7158,NCX17,21.25,Low Fat,0.114066,Health and Hygiene,233.0300,OUT018,2009,Medium,Tier 3,Supermarket Type2,5592.7200
2232,FDT03,21.25,Low Fat,0.009997,Meat,185.5608,OUT035,2004,Small,Tier 2,Supermarket Type1,3123.9336
6223,FDT03,21.25,Low Fat,0.009999,Meat,182.3608,OUT046,1997,Small,Tier 1,Supermarket Type1,551.2824
3632,FDT03,21.25,Low Fat,0.010039,Meat,181.7608,OUT018,2009,Medium,Tier 3,Supermarket Type2,1102.5648
148,FDA45,21.25,Low Fat,0.155350,Snack Foods,178.2370,OUT035,2004,Small,Tier 2,Supermarket Type1,529.3110

## Sorting based on index, sort_index()

In [18]:
data.sort_index(inplace=True)
data.head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
10,FDY07,11.800,Low Fat,0.000000,Fruits and Vegetables,45.5402,OUT049,1999,Medium,Tier 1,Supermarket Type1,1516.0266
11,FDA03,18.500,Regular,0.045464,Dairy,144.1102,OUT046,1997,Small,Tier 1,Supermarket Type1,2187.1530
12,FDX32,15.100,Regular,0.100014,Fruits and Vegetables,145.4786,OUT049,1999,Medium,Tier 1,Supermarket Type1,1589.2646
13,FDS46,17.600,Regular,0.047257,Snack Foods,119.6782,OUT046,1997,Small,Tier 1,Supermarket Type1,2145.2076